languageCode = "en-us"
title = "My Tech Blog"
baseurl = "https://www.vishnu-tech.com/"
theme = "dxb"
disqusShortname = "www-vishnu-tech-com.disqus.com"


[params]
  GithubID = "vishnudxb"
  TwitterID = "vishnudxb"
  LinkedInID = "vishnudxb"
  Name = "Vishnu Nair"
  HeaderUsername = "vishnu"
  HeaderHostname = "VEON"
  Email = "me@vishnudxb.me"
  About = "Vishnu Nair working as Head of DevOps – R&D BigData in VEON, External Board Advisor for Facilitracks and NativeSparrow. He has around over 9+ years of experience in Linux, DevOps, BigData and Cloud Computing Technologies."
  ProfilePicture = "https://media.licdn.com/media/p/8/000/1aa/375/187e4a3.jpg"


[menu]
  [[menu.header]]
    name = "blogs"
    weight = 0
    url = "/blog"

  [[menu.header]]
    name = "about me"
    weight = 1
    url = "/about"


[Permalinks]
    post = "/:year/:month/:day/:filename/"
